### ISSUE TITLE
Реализовать вызов инвентаря

### ISSUE THREAD

**Issue by AlexsSyr** [VaskillerDev/fawe64#39]
Событие для вызова: зажатие кнопки
Визуализация: несколько ячеек в ряд (Как в Зельде дыхание дичи)

**Comment by VaskillerDev** [comment]
Если мы зажмем вторую (свободную) кнопку, допустим в течении 15 тиков, то открывается меню с лотами наших расходников, который выбирается, когда мы эту свободную конпку отпустим

**Comment by VaskillerDev** [comment]
done
